# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rafaelssucupira
# "service" is the name of this project. This will also be added to your AWS resource names.
service: image-analysis-bot

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
     TableName: boxzap
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: "*"   
resources:
  Resources:
    boxzapTable: 
      Type: AWS::DynamoDB::Table
      Properties : 
        TableName : ${self:provider.environment.TableName}
        AttributeDefinitions : 
          - AttributeName: box_id
            AttributeType: S
          - AttributeName: box_data
            AttributeType: S
        KeySchema : 
          - AttributeName: box_id
            KeyType : HASH  
          - AttributeName: box_data
            KeyType : RANGE  
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1   
        GlobalSecondaryIndexes:
          - IndexName: box_data-index
            KeySchema:
              - AttributeName: box_data
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1 


